
on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 2fb11dffaedc5af66b1442b0315c54a4b9da585d
    - name: Install wget
      run: sudo apt-get install wget
    - name: Install nginx
      run: |
        wget http://nginx.org/download/nginx-1.16.1.tar.gz
        tar -xf nginx-1.16.1.tar.gz
    - name: Build C Code
      run: |
        cd nginx-1.16.1
        sudo ./config --add-module=../
        make
